name: INWX-API-Bundle
on: ["push", "pull_request"]
jobs:
    run:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                php-versions: ['7.2', '7.3', '7.4']
                symfony-versions: ['3.4.*', '4.2.*', '4.3.*', '4.4.*', '5.0.*']
        name: PHP ${{ matrix.php-versions }} with Symfony ${{ matrix.symfony-versions }}
        steps:
            -   name: Checkout
                uses: actions/checkout@v2
            -   name: Setup PHP
                uses: shivammathur/setup-php@v1
                with:
                    coverage: xdebug
                    ini-values: memory_limit=1G
                    php-version: ${{ matrix.php-versions }}
            -   name: Get composer cache directory
                id: composer-cache
                run: echo "::set-output name=dir::$(composer config cache-files-dir)"
            -   name: Cache composer dependencies
                uses: actions/cache@v1
                with:
                    path: ${{ steps.composer-cache.outputs.dir }}
                    key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
                    restore-keys: ${{ runner.os }}-composer-
            -   name: Validate composer.json and composer.lock
                run: composer validate
            -   name: Install Symfony
                run: composer require --dev --no-update symfony/framework-bundle:${{ matrix.symfony-versions }}
            -   name: Install dependencies
                run: composer install --prefer-dist --no-progress --no-suggest
            -   name: Run linter
                run: ./vendor/bin/php-cs-fixer fix --diff --dry-run --no-interaction -v
            -   name: Run tests
                run: ./vendor/bin/phpunit -c phpunit.dist.xml
            -   name: Coveralls Parallel
                uses: coverallsapp/github-action@master
                with:
                    github-token: ${{ secrets.COVERALLS_TOKEN }}
                    parallel: true

            -   name: Coveralls Finished
                uses: coverallsapp/github-action@master
                with:
                    github-token: ${{ secrets.COVERALLS_TOKEN }}
                    parallel-finished: true
